**Proactive Crime/Criminal Recognition System**

In [1]:
from google.colab import drive
drive.mount('/content/drive')
%cd drive/My\ Drive
# !pip install mxnet
# !pip install -r requirements.txt
# import pandas as pd
# import numpy as np
# import random as rd
# from collections import Counter
# !pip install autopep8



Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive
/content/drive/My Drive


In [ ]:
!ls

**Face Recognition**

In [ ]:
def facerec():
  !chmod +x tasks/train.sh
  while True:
    !python -m inference.classifier --image-path 'test' --save-dir ' '



**Violence Detection**

In [28]:
import torch
from torch.autograd import Variable
import sys
sys.path.insert(0,'violence-recognition-pytorch/')
from createModel import ViolenceModel
from makeDataset import makeDataset
from spatial_transforms import *
import os
import glob

def violence():

  seqLen=5
  mean=[0.485, 0.456, 0.406]
  std=[0.229, 0.224, 0.225]
  normalize = Normalize(mean=mean, std=std)
  numWorkers=4

  def make_split(fights_dir, noFights_dir):
      imagesF = []
      for target in sorted(os.listdir(fights_dir)):
          d = os.path.join(fights_dir, target)
          if not os.path.isdir(d):
              continue
          imagesF.append(d)
      imagesNoF = []
      for target in sorted(os.listdir(noFights_dir)):
          d = os.path.join(noFights_dir, target)
          if not os.path.isdir(d):
              continue
          imagesNoF.append(d)
      Dataset = imagesF + imagesNoF
      Labels = list([1] * len(imagesF)) + list([0] * len(imagesNoF))
      NumFrames = [len(glob.glob1(Dataset[i], "*.jpg")) for i in range(len(Dataset))]
      return Dataset, Labels, NumFrames

  for i in li:
    model=torch.load('violence-recognition-pytorch/experiments_violence/bestModel.pth')
    model.train=False
    testDataset=[i]
    testLabels=[1,1,1,1,1,0,0,0,0]
    numTestInstances=9
    test_spatial_transform = Compose([Scale(256), CenterCrop(224), FlippedImagesTest(mean=mean, std=std)])
    testBatchSize = 9
    numCorrTest=0 
    testIter = 0
  
    testLossEpoch = 0

    frame_length=[]
    for i in testDataset:
      frame_length.append(len(os.listdir(i))-2)
    #print(frame_length)
    vidSeqTest = makeDataset(testDataset, testLabels, frame_length, seqLen=seqLen,
    spatial_transform=test_spatial_transform)

    testloader=torch.utils.data.DataLoader(vidSeqTest, batch_size=testBatchSize,
                                shuffle=False, num_workers=int(numWorkers/2), pin_memory=True)
    for j,(inputs,targets) in enumerate(testloader):
      testIter += 1

      inputVariable1 = Variable(inputs[0].cuda(), volatile=True)
      outputLabel=model(inputVariable1)
      outputLabel_mean=torch.mean(outputLabel,0,True)
      outputProb = torch.nn.Softmax(dim=1)(outputLabel)
      _, predicted = torch.max(outputProb.data, 1)
      numCorrTest += (predicted == targets[0]).sum()
      
    #predicted.print()
    print(outputProb)
    output.append(predicted)
    testAccuracy = (numCorrTest // numTestInstances) * 100
    avgTestLoss = testLossEpoch // testIter
    #print('Testing: Loss = {} | Accuracy = {}% '.format(avgTestLoss, testAccuracy))



li=['FightDIRTest/95','FightDIRTest/96','FightDIRTest/97','FightDIRTest/98','FightDIRTest/99','nofightDIRTest/newfi96','nofightDIRTest/newfi97','nofightDIRTest/newfi98','nofightDIRTest/newfi99']
output=[]
violence()
print(output)



/usr/local/lib/python3.6/dist-packages/torch/serialization.py:649: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:649: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:649: SourceChangeWarning: source code of class 'torch.nn.modules.activation.ReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set 

tensor([[0.0444, 0.9556],
        [0.0182, 0.9818]], device='cuda:0', grad_fn=<SoftmaxBackward>)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:62: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1625: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1614: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


tensor([[0.0318, 0.9682],
        [0.0361, 0.9639]], device='cuda:0', grad_fn=<SoftmaxBackward>)
tensor([[0.1433, 0.8567],
        [0.1494, 0.8506]], device='cuda:0', grad_fn=<SoftmaxBackward>)
tensor([[0.0498, 0.9502],
        [0.0556, 0.9444]], device='cuda:0', grad_fn=<SoftmaxBackward>)
tensor([[0.0487, 0.9513],
        [0.0240, 0.9760]], device='cuda:0', grad_fn=<SoftmaxBackward>)
tensor([[0.9971, 0.0029],
        [0.9980, 0.0020]], device='cuda:0', grad_fn=<SoftmaxBackward>)
tensor([[0.9934, 0.0066],
        [0.9977, 0.0023]], device='cuda:0', grad_fn=<SoftmaxBackward>)
tensor([[0.9979, 0.0021],
        [0.9987, 0.0013]], device='cuda:0', grad_fn=<SoftmaxBackward>)
tensor([[0.9650, 0.0350],
        [0.9759, 0.0241]], device='cuda:0', grad_fn=<SoftmaxBackward>)
[tensor([1, 1], device='cuda:0'), tensor([1, 1], device='cuda:0'), tensor([1, 1], device='cuda:0'), tensor([1, 1], device='cuda:0'), tensor([1, 1], device='cuda:0'), tensor([0, 0], device='cuda:0'), tensor([0, 0], device='cu

**Jatayu**

In [ ]:
import threading
t1=threading.Thread(target=facerec)
#t2=threading.Thread(target=violence)
t1.start()
#t2.start()
t1.join()
#t2.join()


In [ ]:
!python -m inference.classifier -h --image-path 'test' --save-dir ' '
